### ISSUE TITLE
Feature1 Issue

### ISSUE THREAD

**Issue by BTBIIT** [TXiang-lab/blupADC#1]
Hi, qsmei 
I downloaded your package and tried to use the function.
This is because the features inside it are interesting.
But my real data is not done always with the same error message.
My computer environment is Windows 10, I used RStudio, and the R version is 4.2.0.
The package installation and example data worked properly, and as a result of checking my actual data for analysis, I got the message Error in input_data_vcf[, c(1, 3, 2, 4, 5)]: subscript out of bounds. Same output.
I tried changing the vcf file, I tried using a small size vcf, and the same error was output even when I wrote unannotated raw vcf.
The following pictures are some of the actual data I used.
![image](https://user-images.githubusercontent.com/86939251/170171468-289ce321-05c6-4bba-af24-2f6f96d62808.png)
I couldn't find a note about this in the Description included in your package, and I'm in the process of thinking about how to solve it.
Here's the code I wrote to convert that file.
Please tell me if my code is wrong.

library(blupADC)

phased=geno_format(
  input_data_path="C:/Users/pkh/Desktop/REAL",      
  input_data_name="dp5q20mm100_biA.GBS177.SNP.recode.vcf",  
  input_data_type="VCF",          
  phased_genotype=TRUE,          
  haplotype_window_nSNP=5,      
  bigmemory_cal=TRUE,             
  bigmemory_data_path=getwd(),    
  bigmemory_data_name="test_blupADC", 
  output_data_type=c("Haplotype","Numeric"),
  return_result=TRUE,             
  cpu_cores=2                     
   )

When I run this, I get the following error message:
**Start read the VCF format genotype data 
Complete read the VCF format genotype data 
Error in input_data_vcf[, c(1, 3, 2, 4, 5)] : subscript out of bounds**
Thanks in advance for your advice.

**Comment by qsmei** [comment]
Hi,

Your code is correct. This problem could be the wrong format of vcf data. 
I create a small dataset as you showed in the picture, then i use the same code with you. The function can run without error. 
![image](https://user-images.githubusercontent.com/52848770/170197868-2cffef5b-dbd2-4e4b-af4b-e129bef6cee8.png)

Here is the sample data. 
![image](https://user-images.githubusercontent.com/52848770/170198028-4a035f32-440f-4ab0-b1f7-479d7daeadf5.png)

In terms of your issue, i suggest you tocheck how is the dataset look like after reading into R: str(fread("C:/Users/pkh/Desktop/REAL/dp5q20mm100_biA.GBS177.SNP.recode.vcf",data.table=F)).
 If you still can't solve this problem,  you can send me a small dataset to my email: hzau_qsmei@163.com , i can test and fix it. 

BR
Quanshun

**Comment by BTBIIT** [comment]
@qsmei  
I think your method is right.
A lot of meta information in my data prevented the vcf file from being read.
Like the vcf given as example data, I was able to confirm that it works after reducing the meta information.

However, due to an additional problem, I cannot proceed from Feature2 at all.
For some reason, R prints a Messeage saying "Session Aborted" and goes off with an image of the bomb.

Just in case you ask, is it not possible to use this package in a Windows environment?

Second, in Feature1, I changed the data to hmp type, and it was automatically saved as a txt file.
I tried to perform QC and Imputation on the file, but the above-mentioned off phenomenon was repeated, and the same phenomenon appeared in other formatted PCs even after changing the version of R, reinstalling it.

I'm a little curious if it's because it's a Windows environment, or if I'm missing something.

Your package is really nice, but I think I'm a little clumsy in using it.

*ps: QC_Imputation has output 100% Session Aborted message so far, and QC is about 60% Session Aborted or outputs the following message
> geno_qc_impute(
+  input_data_hmp=LTH_2,    
+  data_analysis_method="QC",
+  output_data_path=getwd(),
+  output_data_name="YY_data",
+  output_data_type="VCF",
+  cpu_cores = 1
+ )   
Start Hapmap to Plink data format conversion......
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Complete Hapmap to Plink data format conversion!
Error in hapmap_convertion(input_data_hmp, type, miss_base, phased_symbol,  : 
  Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'environment'

And when Imputation is selected, 100% R Session Aborted and R encountered a fatal error message is displayed.

Thank you for your advice.

**Comment by qsmei** [comment]
Hi, 

I'm sure the Feature 2 can also be used in windows environment. Looking at the error message, i thought there would be some unexpected characters in hmp data.  
I suggest you can use the example data to test the feature 2:

library(blupADC)
geno_qc_impute(
            input_data_hmp=example_data_hmp,    #provided hapmap data object
            data_analysis_method="QC_Imputation",   #analysis method type,QC + imputatoin
            output_data_path=getwd(),               #output data path
            output_data_name="YY_data",             #output data name
            output_data_type="VCF"                  #output data format 
            ) 


BR
Quanshun
