### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by krr73** [TXiang-lab/blupADC#2]
I'm running macOS Monterey, R 4.2.1. When I try ti install using dev tools I get the following message.

devtools::install_github("TXiang-lab/blupADC")
Downloading GitHub repo TXiang-lab/blupADC@HEAD
✔  checking for file ‘/private/var/folders/6z/wzkwy3zn58b4hq_5rbg7j8f8vzlybl/T/RtmpU6KvCi/remotesdd6b5aa0ca01/TXiang-lab-blupADC-82e59e5/DESCRIPTION’ ...
─  preparing ‘blupADC’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘blupADC’ ...
   ** using staged installation
   ** libs
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c A_G_H.cpp -o A_G_H.o
   A_G_H.cpp:706:31: warning: unused variable 'ind_n2' [-Wunused-variable]
                                   int ind_n1=pos_A11.size(),ind_n2=pos_A22.size(),ind_n=pos_A11.size()+pos_A22.size();
                                                             ^
   A_G_H.cpp:845:31: warning: unused variable 'ind_n2' [-Wunused-variable]
                                   int ind_n1=pos_A11.size(),ind_n2=pos_A22.size(),ind_n=pos_A11.size()+pos_A22.size();
                                                             ^
   A_G_H.cpp:915:31: warning: unused variable 'ind_n2' [-Wunused-variable]
                                   int ind_n1=pos_A11.size(),ind_n2=pos_A22.size(),ind_n=pos_A11.size()+pos_A22.size();
                                                             ^
   3 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c A_G_H_memory.cpp -o A_G_H_memory.o
   A_G_H_memory.cpp:1145:6: warning: unused variable 'tmp2' [-Wunused-variable]
   SEXP tmp2=makeAinv_memory_cpp(Pedigree,bigmemory_data_name+"_temp",bigmemory_data_path);
        ^
   A_G_H_memory.cpp:1169:6: warning: unused variable 'tmp2' [-Wunused-variable]
   SEXP tmp2=makeAinv_memory_cpp(Pedigree,bigmemory_data_name+"_temp",bigmemory_data_path);
        ^
   A_G_H_memory.cpp:1030:6: warning: unused variable 'tmp1' [-Wunused-variable]
   SEXP tmp1=makeA_memory_cpp(Pedigree,bigmemory_data_name+"_temp",bigmemory_data_path);
        ^
   A_G_H_memory.cpp:1236:6: warning: unused variable 'tmp1' [-Wunused-variable]
   SEXP tmp1=makeA_memory_cpp(Pedigree,bigmemory_data_name+"_temp",bigmemory_data_path);
        ^
   4 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c external_function.cpp -o external_function.o
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c haplotype_data_format.cpp -o haplotype_data_format.o
   haplotype_data_format.cpp:102:31: warning: unused variable 'tmp' [-Wunused-variable]
           int n_snp=sum_haplo_type_num,tmp;
                                        ^
   haplotype_data_format.cpp:73:16: warning: unused variable 'n' [-Wunused-variable]
                           int i,j,k,m,n;  
                                       ^
   haplotype_data_format.cpp:73:14: warning: unused variable 'm' [-Wunused-variable]
                           int i,j,k,m,n;  
                                     ^
   haplotype_data_format.cpp:73:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k,m,n;  
                                   ^
   haplotype_data_format.cpp:99:15: warning: unused variable 'ind_pos2' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
                        ^
   haplotype_data_format.cpp:99:6: warning: unused variable 'ind_pos1' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
               ^
   haplotype_data_format.cpp:173:10: warning: unused variable 'j' [-Wunused-variable]
                           int i,j,k;      
                                 ^
   haplotype_data_format.cpp:173:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   8 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c haplotype_data_format_memory.cpp -o haplotype_data_format_memory.o
   haplotype_data_format_memory.cpp:21:28: warning: unused variable 'ind_pos1_num' [-Wunused-variable]
           int ind_pos1,ind_pos2,tmp,ind_pos1_num,ind_pos2_num;
                                     ^
   haplotype_data_format_memory.cpp:21:41: warning: unused variable 'ind_pos2_num' [-Wunused-variable]
           int ind_pos1,ind_pos2,tmp,ind_pos1_num,ind_pos2_num;
                                                  ^
   haplotype_data_format_memory.cpp:345:6: warning: unused variable 'ind_pos1' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
               ^
   haplotype_data_format_memory.cpp:345:15: warning: unused variable 'ind_pos2' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
                        ^
   haplotype_data_format_memory.cpp:320:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k,m,n;  
                                   ^
   haplotype_data_format_memory.cpp:320:14: warning: unused variable 'm' [-Wunused-variable]
                           int i,j,k,m,n;  
                                     ^
   haplotype_data_format_memory.cpp:320:16: warning: unused variable 'n' [-Wunused-variable]
                           int i,j,k,m,n;  
                                       ^
   haplotype_data_format_memory.cpp:348:31: warning: unused variable 'tmp' [-Wunused-variable]
           int n_snp=sum_haplo_type_num,tmp;
                                        ^
   haplotype_data_format_memory.cpp:425:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   haplotype_data_format_memory.cpp:425:10: warning: unused variable 'j' [-Wunused-variable]
                           int i,j,k;      
                                 ^
   10 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c hapmap_data_format.cpp -o hapmap_data_format.o
   hapmap_data_format.cpp:61:55: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   factor_result=pair_base_factor_cpp(snp_vec,miss_base=miss_base);
                                                              ~~~~~~~~~^~~~~~~~~~
   hapmap_data_format.cpp:68:10: warning: unused variable 'status_progress' [-Wunused-variable]
       bool status_progress=true,allele1_status,allele2_status;
            ^
   hapmap_data_format.cpp:148:55: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   factor_result=pair_base_factor_cpp(snp_vec,miss_base=miss_base);
                                                              ~~~~~~~~~^~~~~~~~~~
   hapmap_data_format.cpp:138:55: warning: unused variable 'j' [-Wunused-variable]
           int n_snp=data_hmp.nrow(),n_ind=data_hmp.ncol()-11,i,j,k;
                                                                ^
   hapmap_data_format.cpp:138:57: warning: unused variable 'k' [-Wunused-variable]
           int n_snp=data_hmp.nrow(),n_ind=data_hmp.ncol()-11,i,j,k;
                                                                  ^
   hapmap_data_format.cpp:211:55: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   factor_result=pair_base_factor_cpp(snp_vec,miss_base=miss_base);
                                                              ~~~~~~~~~^~~~~~~~~~
   hapmap_data_format.cpp:304:55: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   factor_result=pair_base_factor_cpp(snp_vec,miss_base=miss_base);
                                                              ~~~~~~~~~^~~~~~~~~~
   7 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c hapmap_plink_numeric_memory.cpp -o hapmap_plink_numeric_memory.o
   hapmap_plink_numeric_memory.cpp:25:55: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   factor_result=pair_base_factor_cpp(snp_vec,miss_base=miss_base);
                                                              ~~~~~~~~~^~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:83:11: warning: variable 'type_number' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
           }else if(type=="double"){
                    ^~~~~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:88:12: note: uninitialized use occurs here
       switch(type_number) {
              ^~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:83:8: note: remove the 'if' if its condition is always true
           }else if(type=="double"){
                 ^~~~~~~~~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:74:20: note: initialize the variable 'type_number' to silence this warning
       int type_number;
                      ^
                       = 0
   hapmap_plink_numeric_memory.cpp:128:62: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                                   temp_base_SNP1=single_base_factor_cpp(temp_vec1,miss_base=miss_base);
                                                                                   ~~~~~~~~~^~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:129:62: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                                   temp_base_SNP2=single_base_factor_cpp(temp_vec2,miss_base=miss_base);
                                                                                   ~~~~~~~~~^~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:188:11: warning: variable 'type_number' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
           }else if(type=="double"){
                    ^~~~~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:194:12: note: uninitialized use occurs here
       switch(type_number) {
              ^~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:188:8: note: remove the 'if' if its condition is always true
           }else if(type=="double"){
                 ^~~~~~~~~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:179:20: note: initialize the variable 'type_number' to silence this warning
       int type_number;
                      ^
                       = 0
   hapmap_plink_numeric_memory.cpp:221:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   hapmap_plink_numeric_memory.cpp:261:11: warning: variable 'type_number' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
           }else if(type=="double"){
                    ^~~~~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:267:12: note: uninitialized use occurs here
       switch(type_number) {
              ^~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:261:8: note: remove the 'if' if its condition is always true
           }else if(type=="double"){
                 ^~~~~~~~~~~~~~~~~~
   hapmap_plink_numeric_memory.cpp:252:20: note: initialize the variable 'type_number' to silence this warning
       int type_number;
                      ^
                       = 0
   7 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c numeric_blupf90.cpp -o numeric_blupf90.o
   numeric_blupf90.cpp:8:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:8:10: warning: unused variable 'j' [-Wunused-variable]
                           int i,j,k;      
                                 ^
   numeric_blupf90.cpp:48:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:102:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:160:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:228:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:262:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:319:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   numeric_blupf90.cpp:380:12: warning: unused variable 'k' [-Wunused-variable]
                           int i,j,k;      
                                   ^
   9 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c plink_data_format.cpp -o plink_data_format.o
   plink_data_format.cpp:56:50: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   temp_SNP1=single_base_factor_cpp(snp1,miss_base=miss_base);
                                                         ~~~~~~~~~^~~~~~~~~~
   plink_data_format.cpp:57:50: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                   temp_SNP2=single_base_factor_cpp(snp2,miss_base=miss_base);
                                                         ~~~~~~~~~^~~~~~~~~~
   plink_data_format.cpp:146:62: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                                   temp_base_SNP1=single_base_factor_cpp(temp_vec1,miss_base=miss_base);
                                                                                   ~~~~~~~~~^~~~~~~~~~
   plink_data_format.cpp:147:62: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                                   temp_base_SNP2=single_base_factor_cpp(temp_vec2,miss_base=miss_base);
                                                                                   ~~~~~~~~~^~~~~~~~~~
   plink_data_format.cpp:235:62: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                                   temp_base_SNP1=single_base_factor_cpp(temp_vec1,miss_base=miss_base);
                                                                                   ~~~~~~~~~^~~~~~~~~~
   plink_data_format.cpp:236:62: warning: explicitly assigning value of variable of type 'std::string' (aka 'basic_string<char>') to itself [-Wself-assign-overloaded]
                                   temp_base_SNP2=single_base_factor_cpp(temp_vec2,miss_base=miss_base);
                                                                                   ~~~~~~~~~^~~~~~~~~~
   plink_data_format.cpp:225:19: warning: unused variable 'j' [-Wunused-variable]
               int i,j,k,n_snp=(data_ped.ncol()-6)/2,n_ind=data_ped.nrow();
                     ^
   7 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c shared_function.cpp -o shared_function.o
   shared_function.cpp:208:28: warning: unused variable 'ind_pos1_num' [-Wunused-variable]
           int ind_pos1,ind_pos2,tmp,ind_pos1_num,ind_pos2_num;
                                     ^
   shared_function.cpp:208:41: warning: unused variable 'ind_pos2_num' [-Wunused-variable]
           int ind_pos1,ind_pos2,tmp,ind_pos1_num,ind_pos2_num;
                                                  ^
   2 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c vcf_data_format.cpp -o vcf_data_format.o
   vcf_data_format.cpp:128:56: warning: unused variable 'm' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,m,n,tmp;
                                                                 ^
   vcf_data_format.cpp:178:15: warning: unused variable 'ind_pos2' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
                        ^
   vcf_data_format.cpp:128:58: warning: unused variable 'n' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,m,n,tmp;
                                                                   ^
   vcf_data_format.cpp:178:6: warning: unused variable 'ind_pos1' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
               ^
   vcf_data_format.cpp:128:60: warning: unused variable 'tmp' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,m,n,tmp;
                                                                     ^
   vcf_data_format.cpp:457:56: warning: unused variable 'allele_num' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,allele_num;
                                                                 ^
   vcf_data_format.cpp:489:10: warning: unused variable 'k' [-Wunused-variable]
           int i,j,k,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,allele_num;
                   ^
   vcf_data_format.cpp:562:58: warning: unused variable 'allele_num' [-Wunused-variable]
           int i,j,k,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,allele_num;
                                                                   ^
   vcf_data_format.cpp:562:10: warning: unused variable 'k' [-Wunused-variable]
           int i,j,k,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,allele_num;
                   ^
   9 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bigmemory/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/R6/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c vcf_data_format_memory.cpp -o vcf_data_format_memory.o
   vcf_data_format_memory.cpp:22:28: warning: unused variable 'ind_pos1_num' [-Wunused-variable]
           int ind_pos1,ind_pos2,tmp,ind_pos1_num,ind_pos2_num;
                                     ^
   vcf_data_format_memory.cpp:22:41: warning: unused variable 'ind_pos2_num' [-Wunused-variable]
           int ind_pos1,ind_pos2,tmp,ind_pos1_num,ind_pos2_num;
                                                  ^
   vcf_data_format_memory.cpp:310:56: warning: unused variable 'allele_num' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,allele_num;
                                                                 ^
   vcf_data_format_memory.cpp:378:56: warning: unused variable 'm' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,m,n,tmp;
                                                                 ^
   vcf_data_format_memory.cpp:378:58: warning: unused variable 'n' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,m,n,tmp;
                                                                   ^
   vcf_data_format_memory.cpp:423:6: warning: unused variable 'ind_pos1' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
               ^
   vcf_data_format_memory.cpp:378:60: warning: unused variable 'tmp' [-Wunused-variable]
           int i,j,n_snp=data_vcf.nrow(),n_ind=data_vcf.ncol()-9,m,n,tmp;
                                                                     ^
   vcf_data_format_memory.cpp:423:15: warning: unused variable 'ind_pos2' [-Wunused-variable]
           int ind_pos1,ind_pos2;  // all types of haplot
                        ^
   8 warnings generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o blupADC.so A_G_H.o A_G_H_memory.o RcppExports.o external_function.o haplotype_data_format.o haplotype_data_format_memory.o hapmap_data_format.o hapmap_plink_numeric_memory.o numeric_blupf90.o plink_data_format.o shared_function.o vcf_data_format.o vcf_data_format_memory.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/opt/gcc/lib -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   installing to /private/var/folders/6z/wzkwy3zn58b4hq_5rbg7j8f8vzlybl/T/RtmpsupaHe/Rinstdf743c434a91/00LOCK-blupADC/00new/blupADC/libs
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   Warning: blupADC-package.Rd:27: All text must be in a section
   Warning: blupADC-package.Rd:28: All text must be in a section
   *** installing help indices
   ** building package indices
   ** testing if installed package can be loaded from temporary location
   Error: package or namespace load failed for ‘blupADC’ in dyn.load(file, DLLpath = DLLpath, ...):
    unable to load shared object '/private/var/folders/6z/wzkwy3zn58b4hq_5rbg7j8f8vzlybl/T/RtmpsupaHe/Rinstdf743c434a91/00LOCK-blupADC/00new/blupADC/libs/blupADC.so':
     dlopen(/private/var/folders/6z/wzkwy3zn58b4hq_5rbg7j8f8vzlybl/T/RtmpsupaHe/Rinstdf743c434a91/00LOCK-blupADC/00new/blupADC/libs/blupADC.so, 0x0006): symbol not found in flat namespace '_omp_set_num_threads'
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing ‘/private/var/folders/6z/wzkwy3zn58b4hq_5rbg7j8f8vzlybl/T/RtmpsupaHe/Rinstdf743c434a91/blupADC’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'blupADC' from GitHub:
  ! System command 'R' failed

**Comment by qsmei** [comment]
Hi,

Hrere is the suggestion from Federico, hope this could help you.

"I did successfully install blupADC on a M1 mac with an arm-64 chip by installing gcc using homebrew and using to following R Makevars:

CC=/opt/homebrew/bin/gcc-11 -fopenmp
CXX=/opt/homebrew/bin/g++-11 -fopenmp
CXX11=/opt/homebrew/bin/g++-11 -fopenmp
CXX14=/opt/homebrew/bin/g++-11 -fopenmp
CXX17=/opt/homebrew/bin/g++-11 -fopenmp
FLIBS=-L/opt/homebrew/opt/gfortran/lib
F77=/opt/homebrew/bin/gfortran
FC=/opt/homebrew/bin/gfortran
CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion CPPFLAGS=-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
CXXFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion

"

BR
Quanshun

**Comment by krr73** [comment]
Thanks, that seems to have worked. I had gcc installed but R was looking in the wrong place. This seems to be a common problem with Macs when compiling from source code.

**Comment by krr73** [comment]
I found this online: https://www.cynkra.com/blog/2021-03-16-gfortran-macos/. It is a problem for Fortran as well.

**Comment by qsmei** [comment]
Ok, thanks for your comments.  I'm not familar with Mac🤣.
