### ISSUE TITLE
More Mac issues

### ISSUE THREAD

**Issue by krr73** [TXiang-lab/blupADC#3]
I was excited to see at least some basic wrapper support for the f90 family of programs from UGA. Unfortunately it looks like blupADC only comes with the windows executables. For future releases it would be good to include the Mac OS executables and provide a straightforward way for users to point to the correct binary files. I was able to get it to work by downloading the Mac executables and putting them in the "bin_windows" folder

**Comment by qsmei** [comment]
Ok. Thanks for your suggestion. 😊

**Comment by dtx282000** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/24269804/236381160-71b08bfa-be79-4cfb-81d6-1cb5b17f1bcf.png">
 when I am loading the blupADC, I also face some problem. How to solve it?

**Comment by qsmei** [comment]
> <img alt="image" width="651" src="https://user-images.githubusercontent.com/24269804/236381160-71b08bfa-be79-4cfb-81d6-1cb5b17f1bcf.png">
> 
> when I am loading the blupADC, I also face some problem. How to solve it?

Hi, 
I am not sure if you have modified the Makevars file in R, if you didn't, maybe you can check the previous issue:https://github.com/TXiang-lab/blupADC/issues/2  
BR
Quanshun
