### ISSUE TITLE
error : subscript out of bounds

### ISSUE THREAD

**Issue by Lixc1219** [TXiang-lab/blupADC#4]
hello,
I encountered this error when using blupADC for SSBLUP: 

Error in `[<-`(`*tmp*`, iteration_pos, 4, value = 1) : 
  subscript out of bounds

Here is my code: 
`library(blupADC)
data_path = "xxx/data1" 
ssgblup = run_DMU(
        phe_path=data_path,
        phe_name="trait1.txt",
        phe_col_names=c("haxdate","ID","trait1"), 
        target_trait_name=list(c("trait1")),
        fixed_effect_name=list(c("haxdate")),
        random_effect_name=list(c("ID")),
        covariate_effect_name=NULL,
        genetic_effect_name="ID",
        integer_n=2,
        analysis_model="SSBLUP_A",
        missing_value=-99,
        dmu_module="dmuai",
        relationship_name=c("pedigree.txt","G_Matrix_new_G_A_col_three.txt"),
        relationship_path=data_path,
        output_result_path=data_path
        )`

Please help us with this matter.
Thanks a lot!

**Comment by qsmei** [comment]
I presume I have fixed this issue in the latest version, please check !
