### ISSUE TITLE
error: no lines available in input

### ISSUE THREAD

**Issue by dtx282000** [TXiang-lab/blupADC#5]
Hi, Dr. Mei,

The R package has been installed on the Mac system. I am currently running the script and encountering an error: no lines available in input.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/24269804/236589445-50cb82af-acf3-4426-844b-a6a799ca4760.png">

Furthermore, the input file has been processed using dos2unix. So, I don't know how to solve it. Thanks!

**Comment by qsmei** [comment]
Hi,

The best way is to check the dmu1.lst and dmuai.lst files, the details of errors are shown in these two files. After checking these two files,  you can send the .lst files to my email: quanshun1994@gmail.com  if you still have problems. 

BR
Quanshun
