### ISSUE TITLE
Error installing on windows

### ISSUE THREAD

**Issue by statslover123** [TXiang-lab/blupADC#6]
I installed the blupSUP already, getting this error when installing blupADC

   installing to C:/Users/schmu/AppData/Local/Temp/Rtmpy4XfaU/Rinst3844229b83f/00LOCK-blupADC/00new/blupADC/libs/x64
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** byte-compile and prepare package for lazy loading
   Warning messages:
   1: package 'data.table' was built under R version 4.2.3 
   2: package 'Rcpp' was built under R version 4.2.3 
   3: package 'RcppArmadillo' was built under R version 4.2.3 
   4: package 'R6' was built under R version 4.2.3 
   ** help
   *** installing help indices
   ** building package indices
   ** testing if installed package can be loaded from temporary location
   Warning: package 'data.table' was built under R version 4.2.3
   Warning: package 'Rcpp' was built under R version 4.2.3
   Warning: package 'RcppArmadillo' was built under R version 4.2.3
   Warning: package 'R6' was built under R version 4.2.3
   Error: package or namespace load failed for 'blupADC' in namespaceExport(ns, exports):
    undefined exports: create_DMU
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing 'C:/Users/schmu/AppData/Local/Temp/Rtmpy4XfaU/Rinst3844229b83f/blupADC'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'blupADC' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by qsmei** [comment]
Hello, 

I appreciate you reporting this issue. This problem has been resolved.  Please reinstall blupADC..

BR,
Quanshun

**Comment by statslover123** [comment]
That solved it, thank you
