### ISSUE TITLE
Random Regression G matrix

### ISSUE THREAD

**Issue by statslover123** [TXiang-lab/blupADC#7]
Is G Matrix format for random regression analysis just inverse?

**Comment by qsmei** [comment]
Yes, it is. User has to provide the inverse of the G matrix for conducting GBLUP analysis with DMU.

**Comment by statslover123** [comment]
Thank you, is there a way to calculate reliability/h2 per time point?

**Comment by qsmei** [comment]
You're welcome. If I remember correctly, the genetic variance of each time point could be calculated as φGφ', where φ is the matrix of Legendre polynomials elements, and G is the genetic  variacne-covaraince matrix. Maybe you can check the related article about random regerssion models.

**Comment by statslover123** [comment]
If I use the blupf90 backend, instead of DMU, the relationship matrix format is different? along with calculation of genetic variance given file output? Which article are you referring to , it might have had the link deleted

**Comment by qsmei** [comment]
You can take a look at the ref: "Invited review: Advances and applications of random regression models: From quantitative genetics to genomics".  Currently, blupADC didn't support random regression analysis with blupf90.

**Comment by statslover123** [comment]
Thank you for the literature 

https://qsmei.netlify.app/post/feature-8-run_blupf90/blupf90/#single-trait----pedigree-blup-model-with-random-regression-effect

In this link there is example of random regression with blupf90 am I mistaken? I will study the DMU option instead

**Comment by qsmei** [comment]
Sorry for the confusion, I made a mistake. I was thought I didn't write the random regression function for blupf90.

**Comment by statslover123** [comment]
Thank you again
